apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      initContainers:
        - name: init-pnpm-install
          image: {{ .Values.image }}
          command: [ "sh", "-c" ]
          args:
            - |
              echo "Running pnpm install"
              cd /app && pnpm install
              cd /app && pnpm run db:migrate
          volumeMounts:
            - name: node-modules-storage
              mountPath: /app/node_modules
            - name: d1-storage
              mountPath: /app/.wrangler
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          volumeMounts:
            - mountPath: /app/node_modules
              name: node-modules-storage
            - mountPath: /app/.wrangler
              name: d1-storage
          command: [ "sh", "-c" ]
          args:
            - |
              pnpm run dev:local
      volumes:
        - name: node-modules-storage
          hostPath:
            path: {{ .Values.sourcepath }}/temp-volume
        - name: d1-storage
          hostPath:
            path: {{ .Values.sourcepath }}/d1-storage
            type: DirectoryOrCreate
