name: Playwright Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test
        env:
          PRIVATE_MONGO_HOST: ${{ secrets.PRIVATE_MONGO_HOST }}
          PRIVATE_MONGO_USER: ${{ secrets.PRIVATE_MONGO_USER }}
          PRIVATE_MONGO_PASS: ${{ secrets.PRIVATE_MONGO_PASS }}
          PRIVATE_MONGO_DB_NAME: ${{ secrets.PRIVATE_MONGO_DB_NAME }}
          PRIVATE_LOCAL_TOOLS_URL: ${{ secrets.PRIVATE_LOCAL_TOOLS_URL }}
          PUBLIC_ENV: ${{ secrets.PUBLIC_ENV }}
          PUBLIC_TOOLS_URL: ${{ secrets.PUBLIC_TOOLS_URL }}
          PUBLIC_INDEX_URL: ${{ secrets.PUBLIC_INDEX_URL }}
          PUBLIC_LIBRARY_URL: ${{ secrets.PUBLIC_LIBRARY_URL }}
          PUBLIC_DATA_PROXY_URL: ${{ secrets.PUBLIC_DATA_PROXY_URL }}
